config/routes.rb
Encounters::Application.routes.draw do

  devise_for :users

  resource :dashboard, only: [:show]
  resource :user, only: [:show] 
  resources :topics, except: [:new]
  resources :contacts do
    resources :encounters, only: [:new]
  end
  resources :encounters, except: [:new,:index] do
    resources :dialogs, except: [ :index]
  end

  root :to => 'dashboards#show'

end

app/models/topic.rb
# == Schema Information
#
# Table name: topics
#
#  id         :integer          not null, primary key
#  title      :string(255)
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  background :text
#

class Topic < ActiveRecord::Base
	belongs_to :user, inverse_of: :topics
	has_many :dialogs, inverse_of: :topic, dependent: :destroy
	has_many :encounters, through: :dialogs
	has_many :contacts, through: :encounters
  attr_accessible :title, :background

  validates :title, presence: true

  default_scope order("updated_at DESC")

  def unique_contacts
#   Contact.joins(:encounters => :dialogs).
#     where("dialogs.topic_id = ?", self.id)
  	contacts.uniq
  end
  
end

app/controllers/topics_controller.rb
class TopicsController < ApplicationController
  # GET /topics
  # GET /topics.json
  def index
    @topics = current_user.topics.all

    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @topics }
    end
  end

  # GET /topics/1
  # GET /topics/1.json
  def show
    @topic = Topic.find(params[:id])   
    #@dialogs = @topic.dialogs.order("encounters.time_of ASC")    
     @dialogs = Dialog.joins(:topic, :encounter => [:contact]).
       where(:topic_id => @topic.id).order("encounters.time_of ASC")    
    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @topic }
      format.js
    end
  end

  # GET /topics/new
  # GET /topics/new.json
  def new
    @topic = current_user.topics.build

    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @topic }
    end
  end

  # GET /topics/1/edit
  def edit
    @topic = Topic.find(params[:id])
  end

  # POST /topics
  # POST /topics.json
  def create
    @topic = current_user.topics.build(params[:topic])
    @encounter = Encounter.find(session[:encounter_key])


    respond_to do |format|
      if @topic.save
        session[:topic_key] = @topic.id
        format.html { redirect_to encounter_path(@encounter), notice: 'Topic was successfully created.' }
        format.json { render json: @topic, status: :created, location: @topic }
      else
        format.html { render action: "new" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /topics/1
  # PUT /topics/1.json
  def update
    @topic = Topic.find(params[:id])

    respond_to do |format|
      if @topic.update_attributes(params[:topic])
        format.html { redirect_to @topic, notice: 'Topic was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @topic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /topics/1
  # DELETE /topics/1.json
  def destroy
    @topic = Topic.find(params[:id])
    @topic.destroy

    respond_to do |format|
      format.html { redirect_to topics_url }
      format.json { head :no_content }
    end
  end
end

app/helpers/topics_helper.rb
module TopicsHelper

end

app/views/topics/_filter_contacts_form.html.erb
<% Contact.joins(:dialogs).select("contacts.*,dialogs.topic_id").where("dialogs.topic_id = ?", topic.id).each do |uc| %>
		<input type="checkbox" checked="checked" class="contact_check" 
			id="contact_<%= uc.id%>">
			<span class="contact" id="contact_<%= uc.id%>"><%= uc.full_name %></span>
	<% end %>

app/views/topics/_form.html.erb
<%= simple_form_for(@topic) do |f| %>
  <%= f.error_notification %>

  <div class="form-inputs">
    <%= f.input :title %>
    <%= f.input :background %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/topics/_topic.html.erb
<div id="<%= dom_id topic %>">
  <h3><%= topic.title %></h3>
  <% if active_encounter %>
    <%= link_to "Add topic to current encounter",
      new_encounter_dialog_path(:encounter_id => active_encounter,
                                :my_topic => {:topic_id => topic.id}),
                               class: 'btn btn-info' %>
  <% end %>
  
  <button class="show_dialogs_btn hide">Show Dialogs</button>
  <%= link_to "Show Dialogs", topic_path(topic),
    class:"topic-dialogs-link", id: dom_id(topic),remote: true %>
  <% unless topic.background.blank? %>
    <div class="background well">
      <h5>Background</h5>
      <%= simple_format topic.background %>
    </div>
  <% end %>
</div>

app/views/topics/edit.html.erb
<h1>Editing topic</h1>

<%= render 'form' %>

<%= link_to 'Show', @topic %> |
<%= link_to 'Back', topics_path %>

app/views/topics/index.html.erb
<h1>Listing topics</h1>

<table>
  <tr>
    <th>Title</th>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @topics.each do |topic| %>
  <tr>
    <td><%= topic.title %></td>
    <td><%= link_to 'Show', topic %></td>
    <td><%= link_to 'Edit', edit_topic_path(topic) %></td>
    <td><%= link_to 'Destroy', topic, method: :delete, data: { confirm: 'Are you sure?' } %></td>
  </tr>
<% end %>
</table>

<br />

app/views/topics/new.html.erb
<h1>New topic</h1>

<%= render 'form' %>

<%= link_to 'Back', topics_path %>

app/views/topics/show.html.erb
<p id="notice"><%= notice %></p>

<h3>Topic: <span><%= @topic.title %></span></h3>
<% unless @topic.background.blank? %>
	<div class="background well">
		<h5>Background</h5>
		<%= simple_format @topic.background %>
	</div>
<% end %>

<div class="dialogs">
	<h4>Dialogs</h4>
	<p>Filter by Contacts: 
		<span id="contact_list">
			<%= render 'filter_contacts_form', :topic => @topic  %>
		</span>
	</p>
		<% @dialogs.each do |d| %>
			<%= render 'dialogs/dialog_for_topic', :dialog => d, :encounter => d.encounter %>
		<% end %>
</div>


<%= link_to 'Edit', edit_topic_path(@topic) %> |
<%= link_to 'Back', :back %>

app/views/topics/show.js.erb
var topic = "div#<%=j dom_id @topic %>"
$(topic).append("<%=j render 'dialogs/dialogs', topic: @topic, dialogs: @dialogs %>")