config/routes.rb
Encounters::Application.routes.draw do

  devise_for :users

  resource :dashboard, only: [:show]
  resource :user, only: [:show] 
  resources :topics, except: [:new]
  resources :contacts do
    resources :encounters, only: [:new]
  end
  resources :encounters, except: [:new,:index] do
    resources :dialogs, except: [ :index]
  end

  root :to => 'dashboards#show'

end

app/models/encounter.rb
# == Schema Information
#
# Table name: encounters
#
#  id         :integer          not null, primary key
#  contact_id :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#  user_id    :integer
#  duration   :integer
#  time_of    :datetime
#  enc_type   :string(255)
#

class Encounter < ActiveRecord::Base
  belongs_to :contact, inverse_of: :encounters
  belongs_to :user, inverse_of: :encounters
  has_many :dialogs, dependent: :destroy, inverse_of: :encounter
  has_many :topics, through: :dialogs
  attr_accessible :time_of, :duration, :contact_id, :enc_type

  TYPE = %w(phone email text in-person other)

  default_scope order("time_of DESC")

  validates :contact_id, presence: true,
  					inclusion: { in: lambda {|enc| enc.user.contacts.map { |c| c.id}}}

  delegate :full_name, to: :contact


end

app/controllers/encounters_controller.rb
class EncountersController < ApplicationController

	def index 
		@encounters = current_user.encounters.all
	end

  def new
    session[:current_encounter] = nil
    @contact = Contact.find(params[:contact_id])
  	@encounter = @contact.encounters.build
  end

  def show
  	@encounter = Encounter.find(params[:id])
  	@dialog = @encounter.dialogs.build
    @topics = current_user.topics.all
  end

  def edit
  	@encounter = Encounter.find(params[:id])
  end

  def create
  	@encounter = current_user.encounters.build(params[:encounter])
  	respond_to do |format|
  		if @encounter.save
  			session[:current_encounter] = @encounter.id
  			format.html { redirect_to @encounter }
  		else
  			format.html do
  				@contacts = current_user.contacts.all
  				render :new
  			end
  		end
  	end
  end
  def update
  	@encounter = current_user.encounters.find(params[:id])
  	respond_to do |format|
  		if @encounter.update_attributes(params[:encounter])
  			format.html do
  				flash[:success] = "Encounter updated" 
  				redirect_to @encounter
  			end
  		else
  			format.html do
  				flash[:error] = "Encounter failed to update"
  				@contacts = current_user.contacts.all
  				render :edit
  			end
  		end
  	end
  end

  def destroy
  	@encounter = current_user.encounters.find(params[:id])
    session[:current_encounter] = nil if @encounter.id == session[:current_encounter]
		@encounter.destroy
  	respond_to do |format|
			format.html do
				flash[:success] = "Encounter destroyed" 
				redirect_to  root_url
			end
		end
  end
end

app/helpers/encounters_helper.rb
module EncountersHelper

end

app/views/encounters/_action_links.html.erb
<p>
	<%= link_to 'edit', edit_encounter_path(encounter), class:'btn' %> 
	<%= link_to 'view', encounter_path(encounter), class:'btn btn-info' %>
	<%= link_to 'delete', encounter_path(encounter), class:'btn btn-danger', method: :delete %>
</p>

app/views/encounters/_encounter.html.erb
<div id="encounter_details" class="well">
	<h6><%= full_name contact %> </h6>
	<p id="time"><span id="type"><%= encounter.enc_type %> -> </span><%= encounter.time_of.strftime("%^B %d at %l:%M %P" ) %></p>
	<%= link_to 'edit',edit_encounter_path(encounter), class:"edit_encounter_link" %> |
	<%= link_to 'delete', encounter_path(encounter), method: :delete, confirm: "Are you sure you want to delete this encounter and all its dialogs?" %>
  <button class="show_topics_btn btn-block btn-info">Show Topics</button>
  <% if encounter.topics.any? %>
    <div id="<%= dom_id encounter %>" class='hide topics'>
      <ul id="<%= dom_id(encounter) %>_topics">
        <% encounter.dialogs.each do |d| %>
          <%= render 'dialogs/dialog', :dialog => d %>
        <% end %>
      </ul>
    </div>
  <% end %>
</div>

app/views/encounters/_encounter_summary.html.erb
<div class="encounter_summary">
		<p><%= encounter.time_of.strftime("%^B %d at %l:%M %P" ) %></p>
		<p>Contact: <%= encounter.full_name %></p>
		<p>Method: <%= encounter.enc_type %></p>
		<p>Topics: <%= encounter.topics.count %></p>
		<%= render 'action_links', :encounter => encounter %>
</div>

app/views/encounters/_form.html.erb
<%= simple_form_for @encounter do |f| %>
  <%= f.association :contact, collection: @contacts,
    label_method: :first_name %>
	<%= f.input :enc_type, collection: Encounter::TYPE, label: false, prompt: 'Select Encounter Method' %>
  <%= f.input :time_of, as: :date %>
  <%= f.input :time_of, as: :time, :ignore_date => true %>
	<%= f.input :duration, label: "Duration(minutes)", collection: (5..60).step(5) %>
	<%= f.submit %>
<% end %>

app/views/encounters/edit.html.erb
<h1>Edit Encounter</h1>
<%= render 'encounters/form' %>

app/views/encounters/new.html.erb
<h3>Create New Encounter</h3>
<%= render 'encounters/form' %>

app/views/encounters/show.html.erb
<%= render 'encounter',:encounter => @encounter %>
<%= render 'dialogs/form', :dialog => @dialog, :encounter => @encounter %>