config/routes.rb
Encounters::Application.routes.draw do

  devise_for :users

  resource :dashboard, only: [:show]
  resource :user, only: [:show] 
  resources :topics, except: [:new]
  resources :contacts do
    resources :encounters, only: [:new]
  end
  resources :encounters, except: [:new,:index] do
    resources :dialogs, except: [ :index]
  end

  root :to => 'dashboards#show'

end

app/models/contact.rb
# == Schema Information
#
# Table name: contacts
#
#  id         :integer          not null, primary key
#  first_name :string(255)
#  last_name  :string(255)
#  company    :string(255)
#  position   :string(255)
#  email      :string(255)
#  phone      :string(255)
#  user_id    :integer
#  created_at :datetime         not null
#  updated_at :datetime         not null
#

class Contact < ActiveRecord::Base
  belongs_to :user, inverse_of: :contacts
  has_many :encounters, dependent: :destroy, inverse_of: :contact
  has_many :topics, through: :encounters
  has_many :dialogs, through: :encounters, dependent: :destroy
  attr_accessible :company, :email, :first_name, :last_name, :phone, :position

  validates :first_name, presence: true
  validates :email, allow_blank: true, format: { with: VALID_EMAIL_REGEX}
  # default_scope where(:user_id => self.user.id)

  #scope :full_stack, -> { includes(:encounters) }

  def full_name
  	"#{first_name} #{last_name}"
  end
end

app/controllers/contacts_controller.rb
class ContactsController < ApplicationController
 
	def index
		@contacts = current_user.contacts.order(:last_name)
	end

	def show
		@contact = Contact.includes(:encounters,:dialogs => :topic).find(params[:id])
    @encounters = @contact.encounters
    @topics = @contact.topics.uniq
	end

	def new
		@contact = current_user.contacts.build
	end

	def edit
		@contact = current_user.contacts.find(params[:id])
	end

	def create
		@contact = current_user.contacts.build(params[:contact])
		respond_to do |format|
			if @contact.save
				session[:contact_key] = @contact.id
				format.html { redirect_to new_contact_encounter_path(@contact) } 
			else
				format.html { render :new }
			end
		end
	end

	def update
		@contact = current_user.contacts.find(params[:id])
		respond_to do |format|
			if @contact.update_attributes(params[:contact])
				flash[:success] = "Contact successfully updated"
				format.html { redirect_to contact_path(@contact)}
			else
				format.html { render 'new'}
			end
		end		
	end

	def destroy
		@contact = current_user.contacts.find(params[:id])
		@contact.destroy
		respond_to do |format|
			format.html { redirect_to contacts_path }		
		end
	end
end

app/helpers/contacts_helper.rb
module ContactsHelper
	def contact_link(contact)
    name = full_name(contact)
		link_to(name, contact_path(contact), class:"contact_link")
	end

  def full_name(contact)
		 "#{contact.first_name} #{contact.last_name}"
  end
end

app/views/contacts/_contact.html.erb
<li>
  <%= link_to_unless_current(contact.first_name, contact_path(contact), 
                             id: dom_id(contact), class: 'contact') do
    link_to(contact.first_name, contact_path(contact), class: 'contact active')
  end
  # ,data: {:'contact-id' => contact.id},remote: true
  %>
</li>

app/views/contacts/_contact_actions.html.erb
<td><%= link_to 'edit', edit_contact_path(contact) %></td>
		<td><%= link_to 'view', contact_path(contact) %></td>
		<td><%= link_to 'delete', contact_path(contact), method: :delete %></td>

app/views/contacts/_contact_list.html.erb
<div class="span2 left_sidebar">
  <ul class="nav nav-list">
    <li class="nav-header"><i class="icon-user"></i>Contacts
      <%= link_to "Add",new_contact_path, id:"add_contact",class:"btn", remote: true %>
    </li>
   <%= render @contacts %>
  </ul>
</div>

app/views/contacts/_form.html.erb
<%= simple_form_for @contact do |f| %>
	<%= f.input :first_name %>
	<%= f.input :last_name %>
	<%= f.input :company %>
	<%= f.input :position %>
	<%= f.input :email %>
	<%= f.input :phone %>
	<%= f.submit  %>
<% end %>

app/views/contacts/_history.html.erb
<%  @contact.encounters.each do |e| %>
  <div>
<%= render e %>
  </div>
<% end %>

app/views/contacts/edit.html.erb
<h2>Edit Contact</h2>
<%= render 'form' %>

app/views/contacts/index.html.erb
<p>This is the <em>Contact's Index page</em> </p>


<table id="contact_list">
	<% @contacts.each do |c| %>
	<tr>
		<td><%= c.first_name + ' ' + c.last_name %></td>
		<%= render 'contacts/contact_actions', :contact => c %>
	</tr>
	<% end %>
</table>

<p><%= link_to "Add Contact", new_contact_path %></p>

app/views/contacts/new.html.erb
<p>This is the new page for contacts</p>
<%= render 'form' %>

app/views/contacts/new.js.erb
    var content = "<%=j render 'contacts/form' %>";
    $('div.main_content').html(content);

app/views/contacts/show.html.erb
<nav class="tab-links">
  <ul>
    <li class="active btn" id="encounters"><a href='#encounters'>Encounters</a></li>
    <li class="btn" id="topics"><a href='#topics'>Topics</a></li>
  </ul>
</nav>
<div class="contacts-data">
  <div class="data-tab" id="encounters-tab">
    <%= render @encounters, :contact => @contact  %>
    
  </div>
  <div class="data-tab" id="topics-tab">
    <% @topics.uniq.each do |t| %>
     <%= render 'topics/topic',:topic => t, :dialogs => t.dialogs %>
    <% end %>
  </div>
</div>
<%= link_to "New Encounter", new_contact_encounter_path(@contact), class: 'btn' %>

app/views/contacts/show.js.erb
var content = '<%=j render "contacts/history"  %>';
$('div.main_content').html(content);