config/routes.rb
Encounters::Application.routes.draw do

  devise_for :users

  resource :dashboard, only: [:show]
  resource :user, only: [:show] 
  resources :topics, except: [:new]
  resources :contacts do
    resources :encounters, only: [:new]
  end
  resources :encounters, except: [:new,:index] do
    resources :dialogs, except: [ :index]
  end

  root :to => 'dashboards#show'

end

app/models/dialog.rb
# == Schema Information
#
# Table name: dialogs
#
#  id           :integer          not null, primary key
#  content      :text
#  encounter_id :integer
#  created_at   :datetime         not null
#  updated_at   :datetime         not null
#  topic_id     :integer
#

class Dialog < ActiveRecord::Base
  belongs_to :encounter, inverse_of: :dialogs
  belongs_to :topic, inverse_of: :dialogs
  
  attr_accessible :content, :topic_id, :new_topic
  attr_accessor :new_topic

  delegate :full_name, :contact, :time_of, :user_id, to: :encounter
  delegate :title, to: :topic

  validates :topic_id, presence: true
  validates :encounter_id, presence: true
  

  scope :by_topic, ->(topic) { where(topic_id: topic) }
  scope :order_by_encounter, -> { joins(:encounter).order('encounters.time_of DESC') }
  before_validation  :create_topic
  

# move this to a service object related to caller
  def create_topic
      t = Topic.create(title: new_topic) if new_topic.present?
      t.update_column(:user_id, self.user_id)
      t.save
      self.topic = t
  end
end

app/controllers/dialogs_controller.rb
class DialogsController < ApplicationController

  def edit
    @encounter = Encounter.find(params[:encounter_id])
    @dialog = Dialog.find(params[:id])
    @topics = current_user.topics.all
    session[:return_to] = request.referer
  end

  def create
    @encounter = Encounter.find(params[:encounter_id])
  	@dialog = @encounter.dialogs.build(params[:dialog])
  	respond_to do |format|
  		if @dialog.save
        #session[:topic_key] = @dialog.topic_id
  			format.html do
  				flash[:success] = "New dialog created"
  				redirect_to encounter_path @encounter
  			end
        format.js
  		else
        format.html do
          flash[:alert] = "Something went wrong. Try again."
          @topics = current_user.topics.all
          render :new
        end
  		end
  	end
  end

  def update
    @dialog = Dialog.find(params[:id])
    @encounter = @dialog.encounter
    respond_to do |format|
      if @dialog.update_attributes(params[:dialog])
        format.html { redirect_to session[:return_to]}
      else
        format.html { render :edit }
      end
    end
  end

  def destroy
    @dialog = Dialog.find(params[:id])
    @dialog.destroy
    respond_to do |format|
      format.html { redirect_to :back}
    end
  end

  private

#  	def set_encounter
#  		@encounter = Encounter.find(session[:encounter_key])
#  	end
end

app/helpers/dialogs_helper.rb
module DialogsHelper
end

app/views/dialogs/_dialog.html.erb
<% unless dialog.changed? %>
	<div class="dialog" id="dialog-<%= dialog.id %>">
		<h4><%= link_to dialog.title,topic_path(dialog.topic), class:"topic_link" %></h4>
			<%= simple_format dialog.content %>
		</p>
		<hr/>
	</div>
<% end %>

app/views/dialogs/_dialog_for_topic.html.erb
<% if dialog.topic %>
	<div class="dialog contact_<%= encounter.contact_id %>" id="dialog_<%= dialog.id %>">
		<p id="time"><span id="type"><%= encounter.enc_type %> &#x2192; </span><%= dialog.time_of.strftime("%l:%M %P on %^b %d, %Y" ) %></p>
		<h6><%= contact_link encounter.contact %> </h6>
			<%= simple_format dialog.content %>
		
		<%= link_to 'edit', edit_encounter_dialog_path(encounter,dialog) %>
		<%= link_to 'delete', encounter_dialog_path(encounter,dialog), method: :delete %>
		<p><%= link_to 'View Encounter', encounter_path(dialog.encounter) %></p>
		<hr/>
	</div>
<% end %>

app/views/dialogs/_dialogs.html.erb
<div class="dialogs hide">
	<h4>Dialogs</h4>
	<p>Filter by Contacts: 
		<span class="contact_list">
			<%= render 'topics/filter_contacts_form', :topic => topic  %>
		</span>
	</p>
  <% if dialogs.any? %>
		<% dialogs.each do |d| %>
			<%= render 'dialogs/dialog_for_topic', :dialog => d, :encounter => d.encounter %>
		<% end %>
  <% end %>
</div>

app/views/dialogs/_form.html.erb
<div id="dialog_form">
		<%= simple_form_for [encounter, dialog] do |f| %>
      <%= f.association :topic, collection: current_user.topics, required: true, label_method: :title,
          prompt:"--Choose a topic--" %>
    or create one:
    <%= f.input :new_topic %>
		<%= f.input :content, label: "What was said?",input_html: {rows:5} %>
		<%= f.submit %>
	<% end %>
</div>

app/views/dialogs/edit.html.erb
<h3>Edit Dialog</h3>
<%= render 'form',:encounter => @encounter, :dialog => @dialog %>

app/views/dialogs/new.html.erb
<h1>Dialogs#new</h1>
<p>Find me in app/views/dialogs/new.html.erb</p>
<%= render 'form', :encounter => Encounter.find(active_encounter),
     :dialog => Dialog.new(params[:my_topic]) %>